FROM tomcat:9.0
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY context.xml /usr/local/tomcat/webapps.dist/manager/META-INF/context.xml
RUN cp -r /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/